# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\KittyHawkStaging\ASSETS\KittyHawk_Data\Tools\3DSMAX\FlightSimPackage\src\scripts\msfs_max_py\AnimationTool\resources\main_view.ui'
#
# Created: Thu Dec  9 16:15:54 2021
#      by: pyside2-uic  running on PySide2 5.6.0a1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(418, 656)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(MainWindow)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(MainWindow)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.leftSuffixLbl = QtWidgets.QLineEdit(MainWindow)
        self.leftSuffixLbl.setObjectName("leftSuffixLbl")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.leftSuffixLbl)
        self.label_2 = QtWidgets.QLabel(MainWindow)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.rightSuffixLbl = QtWidgets.QLineEdit(MainWindow)
        self.rightSuffixLbl.setObjectName("rightSuffixLbl")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.rightSuffixLbl)
        self.label_6 = QtWidgets.QLabel(MainWindow)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_6)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.toggleMirrorDirection = QtWidgets.QPushButton(MainWindow)
        self.toggleMirrorDirection.setObjectName("toggleMirrorDirection")
        self.horizontalLayout.addWidget(self.toggleMirrorDirection)
        self.toggleLabel = QtWidgets.QLabel(MainWindow)
        self.toggleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.toggleLabel.setObjectName("toggleLabel")
        self.horizontalLayout.addWidget(self.toggleLabel)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.line_2 = QtWidgets.QFrame(MainWindow)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.mirrorAnimationBtn = QtWidgets.QPushButton(MainWindow)
        self.mirrorAnimationBtn.setObjectName("mirrorAnimationBtn")
        self.horizontalLayout_3.addWidget(self.mirrorAnimationBtn)
        self.label_7 = QtWidgets.QLabel(MainWindow)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.line = QtWidgets.QFrame(MainWindow)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.frame = QtWidgets.QFrame(MainWindow)
        self.frame.setMinimumSize(QtCore.QSize(0, 80))
        self.frame.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.bakeAnimationBtn = QtWidgets.QPushButton(self.frame)
        self.bakeAnimationBtn.setInputMethodHints(QtCore.Qt.ImhNone)
        self.bakeAnimationBtn.setObjectName("bakeAnimationBtn")
        self.verticalLayout.addWidget(self.bakeAnimationBtn)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.chk_keepExistent = QtWidgets.QCheckBox(self.frame)
        self.chk_keepExistent.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.chk_keepExistent.setObjectName("chk_keepExistent")
        self.horizontalLayout_5.addWidget(self.chk_keepExistent)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.chk_includeChildren = QtWidgets.QCheckBox(self.frame)
        self.chk_includeChildren.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.chk_includeChildren.setObjectName("chk_includeChildren")
        self.horizontalLayout_4.addWidget(self.chk_includeChildren)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.chk_deleteKeysOnSource = QtWidgets.QCheckBox(self.frame)
        self.chk_deleteKeysOnSource.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.chk_deleteKeysOnSource.setObjectName("chk_deleteKeysOnSource")
        self.horizontalLayout_6.addWidget(self.chk_deleteKeysOnSource)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.verticalLayout_2.addWidget(self.frame)
        self.resetScaleBtn = QtWidgets.QPushButton(MainWindow)
        self.resetScaleBtn.setObjectName("resetScaleBtn")
        self.verticalLayout_2.addWidget(self.resetScaleBtn)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.mirrorObjectBtn = QtWidgets.QPushButton(MainWindow)
        self.mirrorObjectBtn.setObjectName("mirrorObjectBtn")
        self.horizontalLayout_2.addWidget(self.mirrorObjectBtn)
        self.mirrorAxis = QtWidgets.QComboBox(MainWindow)
        self.mirrorAxis.setMaximumSize(QtCore.QSize(40, 16777215))
        self.mirrorAxis.setObjectName("mirrorAxis")
        self.mirrorAxis.addItem("")
        self.mirrorAxis.addItem("")
        self.mirrorAxis.addItem("")
        self.horizontalLayout_2.addWidget(self.mirrorAxis)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.mirrorSkinBtn = QtWidgets.QPushButton(MainWindow)
        self.mirrorSkinBtn.setObjectName("mirrorSkinBtn")
        self.verticalLayout_2.addWidget(self.mirrorSkinBtn)
        self.label_13 = QtWidgets.QLabel(MainWindow)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_2.addWidget(self.label_13)
        self.logger = QtWidgets.QTextBrowser(MainWindow)
        self.logger.setObjectName("logger")
        self.verticalLayout_2.addWidget(self.logger)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Animation Tools", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Left suffix", None, -1))
        self.leftSuffixLbl.setText(QtWidgets.QApplication.translate("MainWindow", "_left", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Right suffix", None, -1))
        self.rightSuffixLbl.setText(QtWidgets.QApplication.translate("MainWindow", "_right", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("MainWindow", "WARNING: \n"
"IT IS MANDATORY TO VALIDATE NODES AND LAYERS \n"
"WITH THE VALIDATION TOOL BEFORE USING THIS UTILITY", None, -1))
        self.toggleMirrorDirection.setText(QtWidgets.QApplication.translate("MainWindow", "Toggle Mirror Direction", None, -1))
        self.toggleLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Left To Right", None, -1))
        self.mirrorAnimationBtn.setText(QtWidgets.QApplication.translate("MainWindow", "Mirror Animation", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("MainWindow", "this utility is intented to work with a hierachy of animated bones \n"
"that could evenutally be the parents of UNSKINNED mesh", None, -1))
        self.bakeAnimationBtn.setText(QtWidgets.QApplication.translate("MainWindow", "Convert to Helper animation", None, -1))
        self.chk_keepExistent.setToolTip(QtWidgets.QApplication.translate("MainWindow", "In case an helper with the same name already exist,it will not be deleted", None, -1))
        self.chk_keepExistent.setText(QtWidgets.QApplication.translate("MainWindow", "Keep Existent", None, -1))
        self.chk_includeChildren.setText(QtWidgets.QApplication.translate("MainWindow", "Include Children", None, -1))
        self.chk_deleteKeysOnSource.setText(QtWidgets.QApplication.translate("MainWindow", "Delete Keys On Source And Lods", None, -1))
        self.resetScaleBtn.setText(QtWidgets.QApplication.translate("MainWindow", "Reset Scale", None, -1))
        self.mirrorObjectBtn.setText(QtWidgets.QApplication.translate("MainWindow", "Mirror mesh hierarchy without Skin", None, -1))
        self.mirrorAxis.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "X", None, -1))
        self.mirrorAxis.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "Y", None, -1))
        self.mirrorAxis.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "Z", None, -1))
        self.mirrorSkinBtn.setText(QtWidgets.QApplication.translate("MainWindow", "Mirror Skin", None, -1))
        self.label_13.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Logger</span></p></body></html>", None, -1))

