# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\KH_QA_Release\ASSETS\KittyHawk_Data\Tools\3DSMAX\FlightSimPackage\src\scripts\WiperTool\resources\mainwindow.ui'
#
# Created: Tue Jul 28 17:03:28 2020
#      by: pyside2-uic  running on PySide2 5.6.0a1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_WiperMaskGenerator(object):
    def setupUi(self, WiperMaskGenerator):
        WiperMaskGenerator.setObjectName("WiperMaskGenerator")
        WiperMaskGenerator.resize(622, 764)
        self.verticalLayout = QtWidgets.QVBoxLayout(WiperMaskGenerator)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(WiperMaskGenerator)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 585, 378))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents_2.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents_2.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.formLayout_3 = QtWidgets.QFormLayout(self.scrollAreaWidgetContents_2)
        self.formLayout_3.setObjectName("formLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 360))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 360))
        self.groupBox.setBaseSize(QtCore.QSize(0, 500))
        self.groupBox.setObjectName("groupBox")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout_2.setVerticalSpacing(0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(0, 40))
        self.label_6.setMaximumSize(QtCore.QSize(1999, 37))
        self.label_6.setTextFormat(QtCore.Qt.AutoText)
        self.label_6.setScaledContents(False)
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_6)
        self.sampleImage = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sampleImage.sizePolicy().hasHeightForWidth())
        self.sampleImage.setSizePolicy(sizePolicy)
        self.sampleImage.setMinimumSize(QtCore.QSize(384, 293))
        self.sampleImage.setMaximumSize(QtCore.QSize(384, 293))
        self.sampleImage.setBaseSize(QtCore.QSize(1, 1))
        self.sampleImage.setFrameShape(QtWidgets.QFrame.Box)
        self.sampleImage.setText("")
        self.sampleImage.setPixmap(QtGui.QPixmap("../ui/PlacementInfo.jpg"))
        self.sampleImage.setScaledContents(True)
        self.sampleImage.setAlignment(QtCore.Qt.AlignCenter)
        self.sampleImage.setWordWrap(False)
        self.sampleImage.setObjectName("sampleImage")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.sampleImage)
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.groupBox)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout.addWidget(self.scrollArea)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(WiperMaskGenerator)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_8 = QtWidgets.QLabel(WiperMaskGenerator)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.AnimInStart = QtWidgets.QLineEdit(WiperMaskGenerator)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AnimInStart.sizePolicy().hasHeightForWidth())
        self.AnimInStart.setSizePolicy(sizePolicy)
        self.AnimInStart.setMaximumSize(QtCore.QSize(64, 16777215))
        self.AnimInStart.setObjectName("AnimInStart")
        self.horizontalLayout.addWidget(self.AnimInStart)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.AnimInEndlabel = QtWidgets.QLabel(WiperMaskGenerator)
        self.AnimInEndlabel.setMaximumSize(QtCore.QSize(16777215, 20))
        self.AnimInEndlabel.setObjectName("AnimInEndlabel")
        self.horizontalLayout_2.addWidget(self.AnimInEndlabel)
        self.AnimInEnd = QtWidgets.QLineEdit(WiperMaskGenerator)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AnimInEnd.sizePolicy().hasHeightForWidth())
        self.AnimInEnd.setSizePolicy(sizePolicy)
        self.AnimInEnd.setMaximumSize(QtCore.QSize(64, 16777215))
        self.AnimInEnd.setObjectName("AnimInEnd")
        self.horizontalLayout_2.addWidget(self.AnimInEnd)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_2 = QtWidgets.QLabel(WiperMaskGenerator)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_7.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.AnimOutStart_lbl = QtWidgets.QLabel(WiperMaskGenerator)
        self.AnimOutStart_lbl.setMaximumSize(QtCore.QSize(16777215, 20))
        self.AnimOutStart_lbl.setObjectName("AnimOutStart_lbl")
        self.horizontalLayout_7.addWidget(self.AnimOutStart_lbl)
        self.AnimOutStart = QtWidgets.QLineEdit(WiperMaskGenerator)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AnimOutStart.sizePolicy().hasHeightForWidth())
        self.AnimOutStart.setSizePolicy(sizePolicy)
        self.AnimOutStart.setMaximumSize(QtCore.QSize(64, 16777215))
        self.AnimOutStart.setObjectName("AnimOutStart")
        self.horizontalLayout_7.addWidget(self.AnimOutStart)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_13 = QtWidgets.QLabel(WiperMaskGenerator)
        self.label_13.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_8.addWidget(self.label_13)
        self.AnimOutEnd = QtWidgets.QLineEdit(WiperMaskGenerator)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AnimOutEnd.sizePolicy().hasHeightForWidth())
        self.AnimOutEnd.setSizePolicy(sizePolicy)
        self.AnimOutEnd.setMaximumSize(QtCore.QSize(64, 16777215))
        self.AnimOutEnd.setObjectName("AnimOutEnd")
        self.horizontalLayout_8.addWidget(self.AnimOutEnd)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_6)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_11 = QtWidgets.QLabel(WiperMaskGenerator)
        self.label_11.setMinimumSize(QtCore.QSize(80, 0))
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_9.addWidget(self.label_11)
        self.windshieldNodeName = QtWidgets.QLineEdit(WiperMaskGenerator)
        self.windshieldNodeName.setObjectName("windshieldNodeName")
        self.horizontalLayout_9.addWidget(self.windshieldNodeName)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_10 = QtWidgets.QLabel(WiperMaskGenerator)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(80, 0))
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 80))
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_10.addWidget(self.label_10)
        self.outputPath = QtWidgets.QLineEdit(WiperMaskGenerator)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputPath.sizePolicy().hasHeightForWidth())
        self.outputPath.setSizePolicy(sizePolicy)
        self.outputPath.setObjectName("outputPath")
        self.horizontalLayout_10.addWidget(self.outputPath)
        self.filePathButton = QtWidgets.QPushButton(WiperMaskGenerator)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filePathButton.sizePolicy().hasHeightForWidth())
        self.filePathButton.setSizePolicy(sizePolicy)
        self.filePathButton.setMaximumSize(QtCore.QSize(16777215, 80))
        self.filePathButton.setObjectName("filePathButton")
        self.horizontalLayout_10.addWidget(self.filePathButton)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.line_3 = QtWidgets.QFrame(WiperMaskGenerator)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.wiperConfigurationGroupBox_02 = QtWidgets.QScrollArea(WiperMaskGenerator)
        self.wiperConfigurationGroupBox_02.setMinimumSize(QtCore.QSize(0, 150))
        self.wiperConfigurationGroupBox_02.setMaximumSize(QtCore.QSize(16777215, 270))
        self.wiperConfigurationGroupBox_02.setWidgetResizable(True)
        self.wiperConfigurationGroupBox_02.setObjectName("wiperConfigurationGroupBox_02")
        self.widgetScroll = QtWidgets.QWidget()
        self.widgetScroll.setGeometry(QtCore.QRect(0, 0, 602, 248))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetScroll.sizePolicy().hasHeightForWidth())
        self.widgetScroll.setSizePolicy(sizePolicy)
        self.widgetScroll.setMinimumSize(QtCore.QSize(0, 0))
        self.widgetScroll.setObjectName("widgetScroll")
        self.formLayout = QtWidgets.QFormLayout(self.widgetScroll)
        self.formLayout.setObjectName("formLayout")
        self.wiperConfigurationGroupBox = QtWidgets.QGroupBox(self.widgetScroll)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wiperConfigurationGroupBox.sizePolicy().hasHeightForWidth())
        self.wiperConfigurationGroupBox.setSizePolicy(sizePolicy)
        self.wiperConfigurationGroupBox.setMinimumSize(QtCore.QSize(0, 100))
        self.wiperConfigurationGroupBox.setObjectName("wiperConfigurationGroupBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.wiperConfigurationGroupBox)
        self.wiperConfigurationGroupBox_02.setWidget(self.widgetScroll)
        self.verticalLayout.addWidget(self.wiperConfigurationGroupBox_02)
        self.bakeTexture = QtWidgets.QPushButton(WiperMaskGenerator)
        self.bakeTexture.setMinimumSize(QtCore.QSize(0, 40))
        self.bakeTexture.setObjectName("bakeTexture")
        self.verticalLayout.addWidget(self.bakeTexture)

        self.retranslateUi(WiperMaskGenerator)
        QtCore.QMetaObject.connectSlotsByName(WiperMaskGenerator)

    def retranslateUi(self, WiperMaskGenerator):
        WiperMaskGenerator.setWindowTitle(QtWidgets.QApplication.translate("WiperMaskGenerator", "Wiper Mask Generator", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("WiperMaskGenerator", "MANDATORY", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("WiperMaskGenerator", "Create 2 point helper, parent them to the WiperMesh and position them on the exterior point of the wipe mesh\n"
"It is up to you to define the area impacted by the cleaner part of the wiper \n"
"", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("WiperMaskGenerator", "Animation In:", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("WiperMaskGenerator", "Start Frame", None, -1))
        self.AnimInEndlabel.setText(QtWidgets.QApplication.translate("WiperMaskGenerator", "End Frame", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("WiperMaskGenerator", "Animation Out:", None, -1))
        self.AnimOutStart_lbl.setText(QtWidgets.QApplication.translate("WiperMaskGenerator", "Start Frame", None, -1))
        self.label_13.setText(QtWidgets.QApplication.translate("WiperMaskGenerator", "End Frame", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("WiperMaskGenerator", "Windshield Node", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("WiperMaskGenerator", "Ouput Path", None, -1))
        self.filePathButton.setText(QtWidgets.QApplication.translate("WiperMaskGenerator", "File", None, -1))
        self.wiperConfigurationGroupBox.setTitle(QtWidgets.QApplication.translate("WiperMaskGenerator", "Wipers Configuration", None, -1))
        self.bakeTexture.setText(QtWidgets.QApplication.translate("WiperMaskGenerator", "BakeTexture", None, -1))

