# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\P4v\KittyHawk_WS2\ASSETS\KittyHawk_Data\Tools\3DSMAX\FlightSimPackage\src\scripts\Utilities\SameNameNodeChecker\resources\mainwindow.ui',
# licensing of 'd:\P4v\KittyHawk_WS2\ASSETS\KittyHawk_Data\Tools\3DSMAX\FlightSimPackage\src\scripts\Utilities\SameNameNodeChecker\resources\mainwindow.ui' applies.
#
# Created: Fri May 28 11:08:37 2021
#      by: pyside2-uic  running on PySide2 5.12.5
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_SameNameNodeChecker(object):
    def setupUi(self, SameNameNodeChecker):
        SameNameNodeChecker.setObjectName("SameNameNodeChecker")
        SameNameNodeChecker.setWindowModality(QtCore.Qt.NonModal)
        SameNameNodeChecker.resize(450, 650)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SameNameNodeChecker.sizePolicy().hasHeightForWidth())
        SameNameNodeChecker.setSizePolicy(sizePolicy)
        SameNameNodeChecker.setMinimumSize(QtCore.QSize(450, 650))
        SameNameNodeChecker.setMaximumSize(QtCore.QSize(450, 650))
        SameNameNodeChecker.setFocusPolicy(QtCore.Qt.StrongFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/tbourille/Downloads/a-asobo-blue.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SameNameNodeChecker.setWindowIcon(icon)
        self.verticalLayoutWidget = QtWidgets.QWidget(SameNameNodeChecker)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 451, 651))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setContentsMargins(0, -1, -1, 4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Title = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Title.sizePolicy().hasHeightForWidth())
        self.Title.setSizePolicy(sizePolicy)
        self.Title.setMinimumSize(QtCore.QSize(391, 35))
        self.Title.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Title.setFont(font)
        self.Title.setAlignment(QtCore.Qt.AlignCenter)
        self.Title.setObjectName("Title")
        self.verticalLayout_2.addWidget(self.Title)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(200, 25))
        self.pushButton.setMaximumSize(QtCore.QSize(300, 27))
        self.pushButton.setSizeIncrement(QtCore.QSize(0, 0))
        self.pushButton.setBaseSize(QtCore.QSize(0, 0))
        self.pushButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton.setCheckable(False)
        self.pushButton.setAutoDefault(False)
        self.pushButton.setDefault(False)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.KeepBaseName = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.KeepBaseName.setObjectName("KeepBaseName")
        self.horizontalLayout_4.addWidget(self.KeepBaseName)
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.lineEdit.setMaximumSize(QtCore.QSize(300, 16777215))
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_4.addWidget(self.lineEdit)
        self.suffIncrComb = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.suffIncrComb.setEditable(False)
        self.suffIncrComb.setMaxVisibleItems(5)
        self.suffIncrComb.setModelColumn(0)
        self.suffIncrComb.setObjectName("suffIncrComb")
        self.suffIncrComb.addItem("")
        self.suffIncrComb.addItem("")
        self.suffIncrComb.addItem("")
        self.horizontalLayout_4.addWidget(self.suffIncrComb)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.RenameChecked = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.RenameChecked.setMinimumSize(QtCore.QSize(50, 0))
        self.RenameChecked.setMaximumSize(QtCore.QSize(150, 16777215))
        self.RenameChecked.setObjectName("RenameChecked")
        self.horizontalLayout_2.addWidget(self.RenameChecked)
        self.DeleteChecked = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.DeleteChecked.setMinimumSize(QtCore.QSize(50, 0))
        self.DeleteChecked.setMaximumSize(QtCore.QSize(150, 16777215))
        self.DeleteChecked.setObjectName("DeleteChecked")
        self.horizontalLayout_2.addWidget(self.DeleteChecked)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.NameCopyTab = QtWidgets.QTreeWidget(self.verticalLayoutWidget)
        self.NameCopyTab.setMaximumSize(QtCore.QSize(16777215, 500))
        self.NameCopyTab.setObjectName("NameCopyTab")
        self.NameCopyTab.headerItem().setText(0, "Done")
        self.verticalLayout_2.addWidget(self.NameCopyTab)
        self.ApplyModToScene = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.ApplyModToScene.setObjectName("ApplyModToScene")
        self.verticalLayout_2.addWidget(self.ApplyModToScene)

        self.retranslateUi(SameNameNodeChecker)
        self.suffIncrComb.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(SameNameNodeChecker)

    def retranslateUi(self, SameNameNodeChecker):
        SameNameNodeChecker.setWindowTitle(QtWidgets.QApplication.translate("SameNameNodeChecker", "Dupl node\'s name tool", None, -1))
        self.Title.setText(QtWidgets.QApplication.translate("SameNameNodeChecker", "Dupl node\'s name tool", None, -1))
        self.pushButton.setText(QtWidgets.QApplication.translate("SameNameNodeChecker", "Search for duplicated node names", None, -1))
        self.KeepBaseName.setText(QtWidgets.QApplication.translate("SameNameNodeChecker", "Keep Base name", None, -1))
        self.suffIncrComb.setCurrentText(QtWidgets.QApplication.translate("SameNameNodeChecker", "None", None, -1))
        self.suffIncrComb.setItemText(0, QtWidgets.QApplication.translate("SameNameNodeChecker", "None", None, -1))
        self.suffIncrComb.setItemText(1, QtWidgets.QApplication.translate("SameNameNodeChecker", "_IncrNum", None, -1))
        self.suffIncrComb.setItemText(2, QtWidgets.QApplication.translate("SameNameNodeChecker", "_<Min:sec:msec>", None, -1))
        self.RenameChecked.setText(QtWidgets.QApplication.translate("SameNameNodeChecker", "Rename Checked", None, -1))
        self.DeleteChecked.setText(QtWidgets.QApplication.translate("SameNameNodeChecker", "Delete Checked", None, -1))
        self.NameCopyTab.headerItem().setText(1, QtWidgets.QApplication.translate("SameNameNodeChecker", "in", None, -1))
        self.NameCopyTab.headerItem().setText(2, QtWidgets.QApplication.translate("SameNameNodeChecker", "Code", None, -1))
        self.ApplyModToScene.setText(QtWidgets.QApplication.translate("SameNameNodeChecker", "Apply to Scene", None, -1))

